# client emulator

###
GET http://localhost:5353/api/stock?stock=pltr&password=1234

###
POST http://localhost:5353/api/test
Content-Type: application/json

{
    "message": "hello backend"
}

###
GET http://localhost:5353/api/testParams/123

###

GET https://stock-api-k98u.onrender.com/api/stock?stock=pltr&password=1234